In [3]:
import pandas as pd

# File path to the new HDF5 file with properties
output_hdf5_file = "np_smiles_logp_qed_sas.h5"

# Read the HDF5 file into a DataFrame
df = pd.read_hdf(output_hdf5_file, key='data')

# Display the first few rows of the DataFrame
print(df.head())

                                              smiles    logP       qed  \
0  CC[C@H1](C)[C@@H1](CO)NC(=O)/C=C/[C@@](C)(OC)[...  1.6289  0.397031
1  C=C(C)[C@@H1]1C[C@@]2(C)C(=CC1=O)CC[C@@H1](OC(...  3.6199  0.284499
2  COC1C(C(OC2OC(C(=O)O)=CC(O)C2O)C(N)=O)OC(N3C=C... -4.1700  0.197178
3  O=NC=1[NH1]C(O)=C(C2=CC=CC=C2)C=1C3=CC=C(O)C([...  4.0660  0.378138
4  C[C@@]1(CO)CCC[C@]2(C)[C@H1]3C[C@@]45OC4[C@H1]...  0.9046  0.411117

        SAS
0  4.657218
1  4.813562
2  4.874223
3  2.838857
4  6.111127

In [4]:
df

,smiles,logP,qed,SAS
0,CC[C@H1](C)[C@@H1](CO)NC(=O)/C=C/[C@@](C)(OC)[...,1.62890,0.397031,4.657218
1,C=C(C)[C@@H1]1C[C@@]2(C)C(=CC1=O)CC[C@@H1](OC(...,3.61990,0.284499,4.813562
2,COC1C(C(OC2OC(C(=O)O)=CC(O)C2O)C(N)=O)OC(N3C=C...,-4.17000,0.197178,4.874223
3,O=NC=1[NH1]C(O)=C(C2=CC=CC=C2)C=1C3=CC=C(O)C([...,4.06600,0.378138,2.838857
4,C[C@@]1(CO)CCC[C@]2(C)[C@H1]3C[C@@]45OC4[C@H1]...,0.90460,0.411117,6.111127
...,...,...,...,...
404313,O=C(NCCN=C(O)C(F)(F)C(F)(F)C(F)(F)F)C(F)(F)C(F...,3.72490,0.267920,3.346645
404314,C=CC1=C(C)C2=CC=3[NH1]C(=C(C=CC(=O)O)C=3C)C4=C...,6.47854,0.176203,6.170692
404315,CO[CH0]1[CH1][CH0]([CH0]2[OH1+1][CH0]3[CH1][CH...,-2.94815,0.122223,6.397568
404316,CN(C)C1=CC=C(O)C2=C1CC3CC4C(N(C)C)C(=O)C(C(N)=...,-1.06700,0.480718,4.528286
404317,COCCCC(CC1CCC2(C1)CC3(C)C(CC2O)C(O)CC4C5CCC6C(...,9.67800,0.198940,6.099658